.coafile, .travis.yml, README.md, community/urls.py, community/wsgi.py, gci/config.py, gci/gitorg.py, manage.py
This adds coala configuration for file types currently in the repo.
It also verifies that the word "coala" is never mentioned as to
ensure this repository can be generalized out and used by other
organizations.
Closes https://github.com/coala/community/issues/6
=> .coafile: Add coala configuration

requirements.txt
It is incompatible with django-distill at the moment.
Fixes https://github.com/coala/community/issues/19
=> requirements.txt: Prevent use of Django 2.0

gci/gitorg.py, gci/views.py
closes https://github.com/coala/community/issues/1
=> Addition of favicon and coala logo

.coafile, .travis.yml, activity/index.html, activity/scraper.py, orgname.sh, static/charts.js
Build scraper that scrapes [issues.json from gh-board](https://coala.github.io/gh-board/issues.json) and produces a JSON file just containing stats. This JSON file is used for displaying a static page with graphs, which can be toggled from a dropdown to display past year/month or week's data.
Example page:
<strike>I haven't worked with Django before, so please let me know if something is wrong, or there are better ways to do what I do.</strike> I've since removed all uses of Django, and am deploying it individually since I couldn't get it to work with the rest of the codebase neatly(getting some errors, although it worked fine individually)
The data is processed in python, and not directly in frontend to prevent browser overload(issues.json is > 27 MB)
Closes …
=> activity: Make activity page with graphs on issues

activity/scraper.py, requirements.txt
Fixes previous commit.
Related to https://github.com/coala/community/pull/27
=> activity/scraper: Fix reqs and indexing issues

.coafile
The public/ rendered version contains the word coala,
and thus needs to be ignored from the KeywordBear rule.
Related to https://github.com/coala/community/issues/3
=> .coafile: Ignore public/**

.ci/build.sh, .coafile, .travis.yml
The GCI exported data contains 'coala',
so it needs to be excluded from the relevant checks.
Also ignore private/** and delete it regularly,
as a preventative measure for accidental leaks.
Related to https://github.com/coala/community/issues/3
=> .coafile: Ignore coala in generated GCI files

community/settings.py, community/urls.py, gci/feeds.py, requirements.txt
Creates RSS feed for tasks. Task descriptions are rendered HTML from markdown, along with external URL, if any. Link points to GCI task link.
Closes https://github.com/coala/community/issues/57
=> gci/feeds: Create RSS feed of tasks

activity/scraper.py, community/filters.py, community/settings.py, community/urls.py, gci/gitorg.py, gci/students.py, gci/views.py, log/view_log.py, templates/index.html, twitter/view_twitter.py
This will replace print to standard logging.
It store logs in _site/community.log
Closes https://github.com/coala/community/issues/9
=> Replace print into logging

gci/config.py
Local setting for GCI data directory variable changed to global
using global variable STATIC_ROOT in place of '_site/'
Closes https://github.com/coala/community/issues/71
=> config.py: Use global setting instead of local

community/urls.py, inactive_issues/inactive_issues_scraper.py, requirements.txt, templates/index.html
Add inactive_issues app, currently it work
on coala/coala repo, but to work on any
other repo pass the repository owner name in
`get_organization()` and repository name in
'get_repo()` in `inactive_issues_scraper` file.
=> Add: Inactive Issues app

.ci/deploy.sh, .coafile
*.sh does not match any file.
*.sh --> **.sh.
Fixes https://github.com/coala/community/issues/95
=> .coafile: Check all shell scripts

openhub/models.py
self.project1 -> self.project for MostCommit model
self.project2 -> self.project for MostRecentCommit model
Closes https://github.com/coala/community/issues/116
=> openhub/models.py: Fix str method

README.md
Add instructions of deploying the netlify
on fork of a ``community`` repository.
=> README.md: Add netlify deploy instruction

.gitignore, data/tests/test_management_commands.py
This checks if the real data from the webservices
has 0 records, if it does, it skips all the tests
of the real data.
Fixes https://github.com/coala/community/issues/154
=> test_management_commands.py: Fix webservices error

.coafile, .travis.yml
The YAML had two env: keys.
Related to https://github.com/coala/community/issues/131
=> .travis.yml: Restructure env keys

.gitignore
Adds `prof/` to the `.gitignore` file.
Closes https://github.com/coala/community/issues/156
=> .gitignore: Ignore prof directory

gci/views.py
GCI GitHub cards would display HTML instead of the actual card
element due to an issue upstream. This upgrades the github-cards
dependency to solve this problem.
Fixes https://github.com/coala/community/issues/135
=> gci: Fix GitHub cards failing to render

data/management/commands/import_contributors_data.py
This fix the import_contributors_data command
when the webservices has a server error and our
returned data by the method get_contrib_data is None,
then while iterating through the contributors data
in the management command we need to first check
if the data is not empty to avoid the error:
```
TypeError: 'NoneType' object is not iterable
```
Fixes https://github.com/coala/community/issues/167
=> data/: Fix import_contributors_data command

community/git.py, data/management/commands/fetch_deployed_data.py
git.py : Add name argument to get_upstream_deploy_url method
When fetching the deployed data from the upstream, it tried to fetch
from the current repo even if the data is from a different repo.
Thus adding a repo name argument ensures that the data is fetched
from the repo it is actually in.
Fixes https://github.com/coala/community/issues/185
=> Fix: Issue 185

community/settings.py
This emits warnings and above to stderr, which is useful for
CI logs of the commands being run, and CLI usage of the commands.
Related to https://github.com/coala/community/issues/207
=> settings.py: Add stderr logging of warnings

.moban.yaml, gci/api_actions.py, gci/config.py, gci/issues.py, gci/management/commands/create_issue_tasks.py, gci/management/commands/publish_tasks.py, requirements.txt
Closes https://github.com/coala/community/issues/213
~~Depends on https://github.com/coala/community/issues/204 and https://github.com/coala/community/pull/209 , and https://github.com/coala/community/pull/208 is highly desirable.~~
NOTE: do not mention GCI 2018 tasks here.
TODO:
- ~~use django command instead of `__main__`~~
- ~~use `f`strings throughout~~
- ~~remove the one explicit mentor~~
- ~~store issue metadata in yaml~~
- ~~remove 'coala' from the py~~
DEFERRED:
- mentor username to email lookup, so we can pre-allocate mentors without exposing email addresses here.
- move all the repo specific tags to the yaml, or make generic
=> GCI18 task uploader

.ci/build.sh, .moban.yaml, setup.cfg
openhub app is broken at the moment which
is causing netlify to fail. So, this commit
disables the openhub module until we find out
the problem and fix it.
=> .moban.yaml: Disable openhub module

openhub/views.py, templates/openhub.html
/openhub now shows a short message on how to get an OH_TOKEN if it's not set
Closes https://github.com/coala/community/issues/201
Unsure if having the message in the code like that is okay, but I was unable to think of another way to do it.
=> OpenHub: /openhub shows how to get OH_TOKEN if not set

.moban.yaml, community/views.py, requirements.txt
Fix typo that was causing Travis to fail on master.
Specify specific commit for trav in requirements.txt
to prevent this from happening again.
Fixes https://github.com/coala/community/issues/226
=> views.py: Fix typo referencing wrong Travis env variable

gamification/process/activity_points.py
This fixes the typo and changes
it from touple --> tuple
=> activity_points.py: Fix docstring typo

manage.py
Raise an Exception if python version is < 3.6
Closes https://github.com/coala/community/issues/223
=> manage.py: Raise min python version to 3.6

.gitignore, .moban.yaml, requirements.txt, setup.cfg, test-requirements.txt
The CI builds were failing due to un-synced moban &
latest versions installed of Django and pytest-xdist.
The django v2.1.8 or later version doesn't support
sqlite v3.8.2 anymore which is a pre-installed package
in Ubuntu Trusty. And, latest pytest-xdist needs
pytest v4.4.0 but v3.6.4 is being installed.
Closes https://github.com/coala/community/issues/243
Closes https://github.com/coala/community/issues/241, https://github.com/coala/community/pull/246
=> Install Django v2.1 and Sync moban
