- .coafile
- .travis.yml
- community/settings.py
- gci/views.py
- static/timeago.js
This adds a UTC last generated timestamp to the view as well as how
long ago it was updated.
Closes https://github.com/coala/community/issues/7
> views.py: Add last generated timestamp

- gci/views.py
- requirements.txt
- static/main.css
Closes https://github.com/coala/community/issues/5
> views.py: Add GitHub profile cards

- requirements.txt
Related to https://github.com/coala/community/pull/13
> Add pillow in requirements.txt

- community/urls.py
- templates/index.html
- twitter/view_twitter.py
Addition of twitter feed to main page along with patch to fix the favicon and org logo
Closes https://github.com/coala/community/issues/40
> Addition of twitter feed

- gci/gitorg.py
- gci/management/commands/fetch_old_gci_task_data.py
- gci/students.py
- gci/views.py
Related to https://github.com/coala/community/issues/3
> GCI: Netlify deploys using cached data

- templates/index.html
This modify move the coala logo
Closes https://github.com/coala/community/42
> index.html: move logo

- gci/students.py
- requirements.txt
This detects the authors of the pull requests that close issues in
order to link them with the student who claimed the task.
Finds 3 unlinked users: @nalinbhardwaj, @ravernkoh and @danes44 
Closes https://github.com/coala/community/issues/56
> Detect pull request authors for issues

- .coafile
- activity/scraper.py
- gci/management/commands/cleanse_gci_task_data.py
- gci/students.py
- gci/views.py
Fixes existing errors raised by PyFlakesBear
Closes https://github.com/coala/community/issues/62
> Add pyflakes checking

- data/management/commands/import_contributors_data.py
- data/models.py
Fixes https://github.com/coala/community/issues/108
> Webservices data errors

- requirements.txt
Closes https://github.com/coala/community/issues/118
> Fix broken travis on master

- .coafile
- templates/activity.html
- templates/contributors.html
- templates/index.html
- templates/openhub.html
This adds the HTMLLintBear and its suggested changes.
Closes https://github.com/coala/community/issues/117
> .coafile: Add HTMLLintBear

- community/settings.py
- community/urls.py
- model/apps.py
- model/urls.py
- model/views.py
- openhub/models.py
- templates/contributors.html
- templates/index.html
- templates/model.html
- templates/model/templates/affiliated_committer_detail.html
- templates/model/templates/affiliated_committer_list.html
- templates/model/templates/base.html
- templates/model/templates/organization_detail.html
- templates/model/templates/organization_list.html
- templates/model/templates/outside_committer_detail.html
- templates/model/templates/outside_committer_list.html
- templates/model/templates/outside_project_detail.html
- templates/model/templates/outside_project_list.html
- templates/model/templates/portfolio_project_detail.html
- templates/model/templates/portfolio_project_list.html
- templates/openhub.html
Closes https://github.com/coala/community/issues/87
> Use Generic ListView

- community/urls.py
- templates/index.html
- unassigned_issues/unassigned_issues_scraper.py
List of all the issues on organization
main repository on which someone
opened a PR (with passed ``CI``) without
getting assigned to it.
> Add: Unassigned issue app

- .ci/build.sh
- data/tests/test_management_commands.py
- data/tests/test_models.py
- data/tests/test_views.py
This adds tests for the data app models, views and
management commands.
Closes https://github.com/coala/community/issues/148
> data/tests/: Add tests for data app

- .ci/check_moban.sh
- .coafile
- .gitignore
- .moban.dt/community-gitignore.jj2
- .moban.yaml
- .travis.yml
- test-requirements.txt
Closes https://github.com/coala/community/issues/127
Related to https://gitlab.com/coala/mobans/issues/31
> Use gitignore moban

- .gitignore
Fixes https://github.com/coala/community/issues/161
> Sync gitignore list

- .coafile
- gci/students.py
- inactive_issues/inactive_issues_scraper.py
- openhub/data.py
- test-requirements.txt
Closes https://github.com/coala/community/issues/163
> .coafile: Add PyPluralNamingBear

- .ci/build.sh
- community/git.py
- data/management/commands/fetch_deployed_data.py
- meta_review/dump_to_db.py
- meta_review/handler.py
- meta_review/load_from_db.py
- meta_review/management/commands/run_meta_review_system.py
1. Data needs to be fetched from
https://coala.github.io/gh-board/issues.json.
2. Reaction data needs to be analyzed for scoring and ranking.
3. Result needs to be displayed on the website and stored in the
database.
Closes #142
> Implement meta-review scoring & ranking system

- gci/gitorg.py
This removes an unused variable 'e' from the code.
fixes https://github.com/coala/community/issues/165
> Gitorg.py: Remove unused variable

- data/tests/test_models.py
- setup.cfg
Related to https://github.com/coala/community/issues/176
> setup.cfg: Use Django preferred test_*.py glob

- .nocover.yaml
- data/tests/test_contrib_data.py
- data/tests/test_issues.py
- data/tests/test_merge_requests.py
- setup.cfg
> Get 100% test coverage for data app

- gamification/process/update.py
> Corrected the typo in update.py

- gsoc/models.py
- meta_review/models.py
- requirements.txt
Closes https://github.com/coala/community/issues/182
> Add support for Django 2.x

- .ci/build.sh
- .gitlab-ci.yml
- community/git.py
- community/tests/test_git.py
- data/management/commands/fetch_deployed_data.py
- data/newcomers.py
- templates/index.html
Demo build at https://jayvdb.gitlab.io/community/
One known problem is that second level sub-directory pages do not work.
Pipelines at https://gitlab.com/jayvdb/community/pipelines
> Gitlab support

- .gitignore
- gci/gitorg.py
Fixes https://github.com/coala/community/issues/204
> gci/gitorg.py: Support issues in GitLab suborgs

- .gitignore
- .moban.yaml
- community/urls.py
- community/views.py
- requirements.txt
- templates/index.html
This will only render the Travis build URL if the required
environment variables are set.
Closes https://github.com/coala/community/issues/8
> Add Travis build URL

- test-requirements.txt
> Sync moban templates

- .coafile
- templates/contributors.html
- templates/gamification.html
- templates/index.html
- templates/openhub.html
jinja2bear is added for templates.
Closes https://github.com/coala/community/issues/129
> .coafiles: Add jinja2bear

- .gitignore
- setup.cfg
- test-requirements.txt
The Travis CI moban build is failing
due to outdated files.
Closes https://github.com/coala/community/issues/241
> Sync moban with coala-community repo
